import Head from 'next/head'
import Navbar from '@/src/components/Navbar'
import dynamic from 'next/dynamic'

export default function Home() {
  const Editor = dynamic(() => import('@/src/components/CKEditor/Editor'), { ssr: false })
  return (
    <>
      <Head>
        <title>考題網</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Navbar />
        <Editor value={'Foo'} onChange={(v) => console.log(v)} />
        <button onClick={() => fetch('/api/getFiles')}>取得照片</button>
      </main>
    </>
  )
}
